# Generated by Django 6.0 on 2025-12-23 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish', verbose_name='URL Yolu')),
                ('body', models.TextField(verbose_name='İçerik')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında')], default='draft', max_length=10, verbose_name='Durum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Yazı',
                'verbose_name_plural': 'Yazılar',
                'ordering': ('-publish',),
            },
        ),
    ]
